name: Deployment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        type: boolean
        description: Check to confirm deployment
        required: true
        default: false
      environment:
        description: Environment to be deployed on
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      run: |
        docker build -t my-python-app .
        docker images
