name: Deployment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        type: boolean
        description: Check to confirm deployment
        default: false
        required: true
      environment:
        description: Environment to be deployed on
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == true

    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.vars.outputs.short_ref }}

    - name: Build Docker image
      run: |
        docker build -t my-python-app:${{ steps.vars.outputs.short_ref }} .
        docker images
