name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to be deployed on
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Build Docker image
      run: |
        docker build -t my-python-app:${{ github.ref_name }} .
        docker images
