name: Deployment

on:
  workflow_dispatch:
    inputs:
      confirmation:
        type: boolean
        description: Check to confirm deployment
        default: false
        required: true
      environment:
        description: Environment to be deployed on
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Build Docker image
      run: |
        docker build -t my-python-app:${{ github.ref_name }} .
        docker images
